# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

options:
  docker: true

pipelines:
  branches:
    test:
    # 병렬 실행 하고 싶을 때
    # - parallel:
      - step:
          name: 'Build and Push Docker Image'
          script:
            - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            - docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_APP:latest .
            - docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_APP:latest


      - step:
          name: "send docker-compose.yml"
          script:
            - pipe: atlassian/rsync-deploy:0.8.1
              variables:
                USER: ubuntu
                SERVER: 13.125.241.26
                REMOTE_PATH: ~/data/bifrost-custom-exporter
                LOCAL_PATH: 'docker-compose.yml .env'
            - echo "Deplyment is Completed"
          trigger: automatic




      - step:
          name: 'docker pull & docker-compose up'
          script:
            - pipe: atlassian/ssh-run:0.4.3
              variables:
                SSH_USER: ubuntu
                SERVER: 13.125.241.26
                COMMAND: |
                  sudo docker pull $DOCKER_HUB_USERNAME/$DOCKER_HUB_APP:latest
            - echo "docker pull completed"
          trigger: automatic




