version: '2.18'

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/values.yml:/etc/prometheus/values.yml
    command :
      - '--web.config.file=/etc/prometheus/values.yml'

  bifrost-custom-exporter:
    container_name: bifrost-custom-exporter
    image: cpsehun/bifrost-custom-exporter:latest
    ports:
      - "9000:9000"
    env_file: .env
