version: '2.18'

services:

  prometheus:
    container_name: prometheus  
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  node_exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - "9100:9100"


  bifrost-custom-exporter:
    container_name: bifrost-custom-exporter
    image: cpsehun/bifrost-custom-exporter:latest
    ports:
      - "9000:9000"
    env_file: .env
