global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ['13.125.241.26:9090']

  - job_name: "bifrost-custom-exporter"
    static_configs:
    - targets: ['13.125.241.26:9000']