global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    file_sd_configs:
      - files:
          - values.yml

  - job_name: "bifrost-custom-exporter"
    file_sd_configs:
      - files:
          - values.yml
